backend/controllers/SensordataController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\SensorData;
use backend\searchModels\SensordataSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * SensordataController implements the CRUD actions for SensorData model.
 */
class SensordataController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all SensorData models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SensordataSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single SensorData model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new SensorData model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new SensorData();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing SensorData model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing SensorData model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the SensorData model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return SensorData the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = SensorData::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">

    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
//                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
       
    </div>
    <strong>Copyright &copy; <?=date('Y')?> TK-01. </strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->

backend/views/layouts/header.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

<?= Html::a('<span class="logo-mini"></span><span class="logo-lg"> Agrimon</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
                    <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= Yii::$app->homeUrl ?>/img/person.png" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?=Yii::$app->user->identity->username?></span>
                    </a>-->
					<?=
                                Html::a(
                                        '<i class="glyphicon glyphicon-log-out"></i><span> Sign Out', ['/site/logout'], ['data-method' => 'post', ]
                                )
                                ?>
					
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= Yii::$app->homeUrl ?>/img/person.png" class="img-circle"
                                 alt="User Image"/>

                            <p>
                                Welcome <?=Yii::$app->user->identity->username?>
                                <small>Sistem Informasi BTA 13 </small>
                            </p>
                        </li>
                        
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                
                            </div>
                            <div class="pull-right">
                                <?=
                                Html::a(
                                        'Sign out', ['/site/logout'], ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                )
                                ?>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

backend/views/layouts/left.php
<?php

use yii\bootstrap\Nav;
use yii\widgets\Menu;
?>


<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= Yii::$app->homeUrl ?>/img/person.png" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->identity->username ?></p>

                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>



        <?php
        echo Menu::widget([
            'options' => ['class' => 'sidebar-menu'],
            'submenuTemplate' => "\n<ul class=\"treeview-menu\">\n{items}\n</ul>\n",
            'activateParents' => true,
            'activateItems' => true,
            'encodeLabels' => false,
            'items' => [

                [
                    'label' => '<i class="glyphicon glyphicon-home"></i><span> Home</span> ',
                    'url' => ['site/index']
                ],
                [
                    'label' => '<i class="fa  fa-gears"></i><span> Manajemen </span><i class="fa fa-angle-left pull-right"></i>',
                    'url' => ['#'],
                    'items' => [
                        [
                            'label' => '<i class="fa  fa-list-alt"></i><span> Daftar Sensor</span> ',
                            'url' => ['sensoravailable/index'],
                            'active' => Yii::$app->controller->id == "sensoravailable",
                        ],
                        [
                            'label' => '<i class="fa  fa-list-alt"></i><span> Daftar Aktuator</span> ',
                            'url' => ['actuatoravailable/index'],
                            'active' => Yii::$app->controller->id == "actuatoravailable",
                        ],
                        [
                            'label' => '<i class="fa  fa-wrench"></i><span> Konfigurasi Utama</span> ',
                            'url' => ['/generalconfiguration/view', 'id' => base64_encode(Yii::$app->generalConf->confid())],
                            'active' => Yii::$app->controller->id == "generalconfiguration",
                        ],
//                        [
//                            'label' => '<i class="fa   fa-bar-chart"></i><span> Data Hasil </span>',
//                            'url' => ['sensordata/index'],
//                            'active' => Yii::$app->controller->id == "sensordata",
//                        ],
                        [
                            'label' => '<i class="fa  fa-user"></i><span> Ganti Password',
                            'url' => ['/update-pass/changepass', 'id' => base64_encode(Yii::$app->user->id)],
                            'active' => Yii::$app->controller->id == "update-pass",
                        ],
                    ]
                ],
//                [
//                    'label' => '<i class="glyphicon glyphicon-saved"></i><span> Gunakan Sensor </span>',
//                    'url' => ['sensorinuse/index'],
//                    'active' => Yii::$app->controller->id == "sensorinuse",
//                ],
//                [
//                    'label' => '<i class="fa   fa-bar-chart"></i><span> Data Hasil </span>',
//                    'url' => ['sensordata/index'],
//                    'active' => Yii::$app->controller->id == "sensordata",
//                ],
                [
                    'label' => '<i class="fa  fa-wrench"></i><span> Manajemen Sensor</span>',
                    'url' => ['finalconfiguration/index'],
                    'active' => Yii::$app->controller->id == "finalconfiguration",
                ],
            ],
        ]);
        ?>




    </section>

</aside>

backend/views/layouts/main-login.php
<?php

use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
<?php $this->head() ?>
    </head>
    <body class="login-page">

        <?php $this->beginBody() ?>

        <?= $content ?>

<?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


if (Yii::$app->controller->action->id === 'login') {
    /**
     * Do not use this code in your template. Remove it. 
     * Instead, use the code  $this->layout = '//main-login'; in your controller.
     */
    echo $this->render(
            'main-login', ['content' => $content]
    );
} else {

    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
        <head>
            <meta charset="<?= Yii::$app->charset ?>"/>
            <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
            <meta name="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
            <?= Html::csrfMetaTags() ?>
            <title><?= Html::encode($this->title) ?></title>
            <?php $this->head() ?>
        </head>
        <body class="hold-transition <?= \dmstr\helpers\AdminLteHelper::skinClass() ?> layout-boxed ">
            <!--<body class="hold-transition skin-blue  sidebar-mini">-->
            <?php $this->beginBody() ?>
            <div class="wrapper">

                <?=
                $this->render(
                        'header.php', ['directoryAsset' => $directoryAsset]
                )
                ?>

                <?=
                $this->render(
                        'left.php', ['directoryAsset' => $directoryAsset]
                )
                ?>

                <?=
                $this->render(
                        'content.php', ['content' => $content, 'directoryAsset' => $directoryAsset]
                )
                ?>

            </div>

            <?php $this->endBody() ?>
        </body>
    </html>
    <?php $this->endPage() ?>
<?php } ?>